In [3]:
import tensorflow as tf

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

X = tf.placeholder(tf.float32, shape = [None,3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W)+b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict = {X:x_data, Y:y_data})
    if step % 20 == 0 :
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  138518.0 
Prediction:
 [[-182.74195862]
 [-209.91642761]
 [-212.32301331]
 [-226.96791077]
 [-160.91633606]]
20 Cost:  6.84694 
Prediction:
 [[ 147.4954071 ]
 [ 186.97970581]
 [ 178.75845337]
 [ 198.90644836]
 [ 141.81230164]]
40 Cost:  6.81657 
Prediction:
 [[ 147.51144409]
 [ 186.97462463]
 [ 178.76629639]
 [ 198.91146851]
 [ 141.80531311]]
60 Cost:  6.78646 
Prediction:
 [[ 147.52438354]
 [ 186.96592712]
 [ 178.77047729]
 [ 198.91252136]
 [ 141.795578  ]]
80 Cost:  6.75668 
Prediction:
 [[ 147.53729248]
 [ 186.95733643]
 [ 178.77471924]
 [ 198.91365051]
 [ 141.78591919]]
100 Cost:  6.72714 
Prediction:
 [[ 147.55007935]
 [ 186.94871521]
 [ 178.77886963]
 [ 198.91465759]
 [ 141.77629089]]
120 Cost:  6.69789 
Prediction:
 [[ 147.56283569]
 [ 186.94017029]
 [ 178.78303528]
 [ 198.91571045]
 [ 141.76675415]]
140 Cost:  6.66891 
Prediction:
 [[ 147.57553101]
 [ 186.93167114]
 [ 178.78717041]
 [ 198.91674805]
 [ 141.75726318]]
160 Cost:  6.6402 
Prediction:
 [[ 147.58816528]
 [ 1

1600 Cost:  5.13137 
Prediction:
 [[ 148.34890747]
 [ 186.41575623]
 [ 179.04231262]
 [ 198.96032715]
 [ 141.19918823]]
1620 Cost:  5.11638 
Prediction:
 [[ 148.35766602]
 [ 186.40994263]
 [ 179.04522705]
 [ 198.96054077]
 [ 141.19316101]]
1640 Cost:  5.10153 
Prediction:
 [[ 148.3664093 ]
 [ 186.40419006]
 [ 179.04815674]
 [ 198.96078491]
 [ 141.18719482]]
1660 Cost:  5.08679 
Prediction:
 [[ 148.37504578]
 [ 186.39839172]
 [ 179.05104065]
 [ 198.96095276]
 [ 141.18121338]]
1680 Cost:  5.0722 
Prediction:
 [[ 148.38366699]
 [ 186.39265442]
 [ 179.0539093 ]
 [ 198.96115112]
 [ 141.17529297]]
1700 Cost:  5.05769 
Prediction:
 [[ 148.39228821]
 [ 186.38699341]
 [ 179.05682373]
 [ 198.96136475]
 [ 141.16943359]]
1720 Cost:  5.04333 
Prediction:
 [[ 148.40081787]
 [ 186.38131714]
 [ 179.05967712]
 [ 198.96153259]
 [ 141.16357422]]
1740 Cost:  5.02905 
Prediction:
 [[ 148.40931702]
 [ 186.37565613]
 [ 179.06251526]
 [ 198.96168518]
 [ 141.15776062]]
1760 Cost:  5.01487 
Prediction:
 [[ 148.

In [4]:
import numpy as np


In [6]:
xy = np.loadtxt('data-01-test-score.csv',delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data, len(y_data))


(25, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 25
(25, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]] 25


In [7]:
filename_queue = tf.train.string_input_producer(
['data-01-test-score.csv'], shuffle = False, name = 'filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)
    